version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_migracao_dados
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: migracao_dados
      MYSQL_USER: fatura
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../../../files/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

volumes:
  db_data: